inherit_gem:
  deka_eiwakun: "config/rubocop.yml"

AllCops:
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Metrics/AbcSize:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 160

Metrics/MethodLength:
  Max: 30

Metrics/PerceivedComplexity:
  Max: 10

Style/AndOr:
  EnforcedStyle: conditionals

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ParallelAssignment:
  Enabled: false

Style/StringLiterals:
  Exclude:
    - '**/bin/**/*'

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInLiteral:
  Enabled: false

Style/UnlessElse:
  Enabled: false
