pins:
  infrared_sensor: 18
  distance_sensor:
    trig: 17
    echo: 27

room:
  name: 俺の席
  distance: 100 # cm

notifiers:
  - FrontDesk::IdobataNotifier
  - FrontDesk::YukkuriNotifier

idobata:
  url: https://idobata.io/hook/custom/d74c5697-d6dc-489a-b6d1-bcb5525015f8
