pins:
  infrared_sensor: 18
  distance_sensor:
    trig: 17
    echo: 27
  led: 25

room:
  name: 俺の席
  distance: 100 # cm

notifiers:
  - FrontDesk::IdobataNotifier
  - FrontDesk::SlackNotifier
  - FrontDesk::YukkuriNotifier
  - FrontDesk::LEDNotifier

idobata:
  url: 'hook url'

slack:
  url: 'hook url'
